(function() {var implementors = {};
implementors["framecodecs"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='framecodecs/fixed_length/struct.FixedLengthProto.html' title='framecodecs::fixed_length::FixedLengthProto'>FixedLengthProto</a>","impl&lt;D:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='framecodecs/delimiter/struct.DelimiterProto.html' title='framecodecs::delimiter::DelimiterProto'>DelimiterProto</a>&lt;D&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='framecodecs/delimiter/enum.LineDelimiter.html' title='framecodecs::delimiter::LineDelimiter'>LineDelimiter</a>","impl&lt;B:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='framecodecs/length_field/struct.LengthFieldProto.html' title='framecodecs::length_field::LengthFieldProto'>LengthFieldProto</a>&lt;B&gt;","impl&lt;C:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a>, Kind:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='framecodecs/remote_addr/struct.RemoteAddrProto.html' title='framecodecs::remote_addr::RemoteAddrProto'>RemoteAddrProto</a>&lt;C, Kind&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
